basePath: /api
consumes:
    - application/json
info:
    description: |-
        ## Сервис Конвеера заявок Хумо для работы с внешними платформами

        Данный сервис был создан чтобы сделать Application не зависимым от других платформ, единственное что можно будет заменять это его Bridge (от англ. Мост)
    title: Application Bridge
    version: 0.0.1
paths:
    /auth/login:
        post:
            description: |-
                ## Роут предназначен для авторизации ранее зарегистрированного пользователя
                Используемый <b>Authorization Flow</b> подразумевает сначала проверка введенных пользователем <b>credential</b> (phone, password)
                После успешной проверки, пользователю высылается на номер телефона OTP код с временем жизни в <code>1 минуту</code>
            operationId: authLogin
            parameters:
                - in: body
                  name: Body
                  schema:
                    properties:
                        code:
                            default: "1234"
                            description: Одноразовый код
                            maxLength: 4
                            type: string
                            x-go-name: Code
                        password:
                            default: '!qwerty123'
                            description: Пароль
                            maxLength: 100
                            minLength: 8
                            type: string
                            x-go-name: Password
                        phone:
                            default: "992000331341"
                            description: Телефонный номер
                            pattern: 992\d{9}$
                            type: string
                            x-go-name: Phone
                    required:
                        - code
                        - password
                        - phone
                    type: object
            responses:
                "200":
                    description: '## Успешная авторизаиця'
                    schema:
                        $ref: '#/responses/success/schema'
                "400":
                    description: |-
                        ## Неверный запрос
                        Возможно, вам стоит перепроверить введенные данные

                        Все возможные сообщения об ошибках в полезной нагрузке (payload):
                        <ul>
                          <li>Не верный OTP код</li>
                          <li>Неправильный логин или пароль</li>
                          <li>Одно или несколько полей пустые</li>
                        </ul>
                    schema:
                        $ref: '#/responses/badRequest/schema'
                "429":
                    description: |-
                        ## Retry Limit Exceeded
                        Количество попыток: <code>4</code>
                        Сбросить лимит после <code>5 минуты</code>
                    schema:
                        $ref: '#/responses/retryLimitExceeded/schema'
                "500":
                    description: Internal Server Error or Something went wrong
                    schema:
                        $ref: '#/responses/internalServer/schema'
            summary: Вход в платформу
            tags:
                - Authorization
    /ping:
        get:
            description: '## A simple router to check server status'
            operationId: ping
            responses:
                "200":
                    description: "## Pong ! \U0001F94E"
                    schema:
                        $ref: '#/responses/ping/schema'
            summary: Ping Pong!
            tags:
                - Ping
produces:
    - application/json
responses:
    accessDenied:
        description: ""
        schema:
            properties:
                message:
                    example: access is denied
                    type: string
                    x-go-name: Message
                payload:
                    example: "null"
                    x-go-name: Payload
            type: object
    badRequest:
        description: ""
        schema:
            properties:
                message:
                    example: bad request
                    type: string
                    x-go-name: Message
                payload:
                    example: "null"
                    x-go-name: Payload
            type: object
    conflict:
        description: ""
        schema:
            properties:
                message:
                    example: conflict
                    type: string
                    x-go-name: Message
                payload:
                    example: "null"
                    x-go-name: Payload
            type: object
    internalServer:
        description: ""
        schema:
            properties:
                message:
                    example: internal server error
                    type: string
                    x-go-name: Message
                payload:
                    example: "null"
                    x-go-name: Payload
            type: object
    notFound:
        description: ""
        schema:
            properties:
                message:
                    example: notFound
                    type: string
                    x-go-name: Message
                payload:
                    example: "null"
                    x-go-name: Payload
            type: object
    notImplementation:
        description: ""
        schema:
            properties:
                message:
                    example: not implementation
                    type: string
                    x-go-name: Message
                payload:
                    example: "null"
                    x-go-name: Payload
            type: object
    ping:
        description: Ping
        headers:
            Data: {}
        schema:
            properties:
                message:
                    example: Успешно
                    type: string
                    x-go-name: Message
                payload:
                    example: Clean arch pong!
                    type: string
                    x-go-name: Payload
            type: object
    retryLimitExceeded:
        description: ""
        schema:
            properties:
                message:
                    example: retry limit exceeded
                    type: string
                    x-go-name: Message
                payload:
                    example: "null"
                    x-go-name: Payload
            type: object
    somethingWentWrong:
        description: ""
        schema:
            properties:
                message:
                    example: something went wrong
                    type: string
                    x-go-name: Message
                payload:
                    example: "null"
                    x-go-name: Payload
            type: object
    success:
        description: ""
        schema:
            properties:
                message:
                    example: success
                    type: string
                    x-go-name: Message
                payload:
                    example: "null"
                    x-go-name: Payload
            type: object
    unauthorized:
        description: ""
        schema:
            properties:
                message:
                    example: unauthorized
                    type: string
                    x-go-name: Message
                payload:
                    example: "null"
                    x-go-name: Payload
            type: object
securityDefinitions:
    Bearer:
        in: header
        name: Authorization
        type: apiKey
swagger: "2.0"
