basePath: /api
consumes:
    - application/json
info:
    description: |-
        ## Сервис web-кошелька

        Данный сервис был создан для того чтобы показать преимущества и простоту использования web-кошельков
    title: eWallet
    version: 0.0.1
paths:
    /auth/login:
        post:
            description: |-
                ## Роут предназначен для авторизации ранее зарегистрированного пользователя

                Используемый <b>Authorization Flow</b> подразумевает сначала проверка введенных пользователем <b>credential</b> (phone, password)
            operationId: authLogin
            parameters:
                - in: body
                  name: Body
                  schema:
                    properties:
                        password:
                            default: '!qwerty123'
                            description: Пароль
                            maxLength: 100
                            minLength: 8
                            type: string
                            x-go-name: Password
                        phone_number:
                            default: "992911170603"
                            description: Телефонный номер
                            pattern: 992\d{9}$
                            type: string
                            x-go-name: Phone
                    required:
                        - password
                        - phone_number
                    type: object
            responses:
                "200":
                    description: '## Успешная авторизаиця'
                    schema:
                        $ref: '#/responses/success/schema'
                "400":
                    description: |-
                        ## Неверный запрос
                        Возможно, вам стоит перепроверить введенные данные

                        Все возможные сообщения об ошибках в полезной нагрузке (payload):
                        <ul>
                          <li>Неправильный логин или пароль</li>
                          <li>Одно или несколько полей пустые</li>
                        </ul>
                    schema:
                        $ref: '#/responses/badRequest/schema'
                "500":
                    description: Internal Server Error or Something went wrong
                    schema:
                        $ref: '#/responses/internalServer/schema'
            summary: Вход в систему
            tags:
                - Authorization
    /auth/otp-verify:
        post:
            description: |-
                ## Роут предназначен для подтверждения номера телефона пользователя после регистрации.
                Используемый <b>OTP Verification Flow</b> подразумевает, что пользователь вводит полученный OTP-код, который был отправлен на его номер телефона.
                Время жизни OTP-кода составляет <code>5 минут</code>. Если код подтверждения правильный, пользователь может продолжить процесс регистрации или авторизации.
            operationId: authOTPVerify
            parameters:
                - in: body
                  name: Body
                  schema:
                    properties:
                        otp_code:
                            default: "1234"
                            description: Одноразовый код
                            maxLength: 4
                            type: string
                            x-go-name: Code
                        phone_number:
                            default: "992911170603"
                            description: Телефонный номер
                            pattern: 992\d{9}$
                            type: string
                            x-go-name: Phone
                    required:
                        - phone_number
                        - otp_code
                    type: object
            responses:
                "200":
                    description: '## Успешная авторизация'
                    schema:
                        $ref: '#/responses/success/schema'
                "400":
                    description: |-
                        ## Неверный запрос
                        Возможно, вам стоит перепроверить введенные данные

                        Все возможные сообщения об ошибках в полезной нагрузке (payload):
                        <ul>
                          <li>Неверный OTP код</li>
                          <li>Неправильный логин или пароль</li>
                        </ul>
                    schema:
                        $ref: '#/responses/badRequest/schema'
                "500":
                    description: Internal Server Error or Something went wrong
                    schema:
                        $ref: '#/responses/internalServer/schema'
            summary: Подтверждение номера телефона пользователя по OTP после регистрации
            tags:
                - Authorization
    /auth/refresh:
        post:
            description: |-
                ## Роут предназначен для получения новой пары токенов (access и refresh) по действующему refresh-токену.

                Пользователь должен передать refresh токен в теле запроса.
                Access токен не требуется.
            operationId: authRefreshToken
            parameters:
                - in: body
                  name: Body
                  schema:
                    properties:
                        refresh_token:
                            default: test
                            description: Рефреш токен
                            type: string
                            x-go-name: RefreshToken
                    required:
                        - refresh_token
                    type: object
            responses:
                "200":
                    description: '## Успешная авторизаиця'
                    schema:
                        $ref: '#/responses/success/schema'
                "400":
                    description: |-
                        ## Неверный запрос
                        Возможно, вам стоит перепроверить введенные данные

                        Все возможные сообщения об ошибках в полезной нагрузке (payload):
                        <ul>
                          <li>Отсутствует refresh токен</li>
                          <li>Невалидный формат токена</li>
                        </ul>
                    schema:
                        $ref: '#/responses/badRequest/schema'
                "401":
                    description: '## Недействительный или просроченный refresh токен'
                    schema:
                        $ref: '#/responses/unauthorized/schema'
                "429":
                    description: |-
                        ## Retry Limit Exceeded
                        Количество попыток: <code>4</code>
                        Сбросить лимит после <code>5 минуты</code>
                    schema:
                        $ref: '#/responses/retryLimitExceeded/schema'
                "500":
                    description: Internal Server Error or Something went wrong
                    schema:
                        $ref: '#/responses/internalServer/schema'
            summary: Обновление токенов
            tags:
                - Authorization
    /auth/registration:
        post:
            description: |-
                ## Роут предназначен для регистрации нового пользователя в системе
                Используемый <b>Registration Flow</b> подразумевает отправку номера телефона и пароля
                После получения данных, на указанный номер телефона отправляется OTP-код для подтверждения личности
                Время жизни OTP-кода составляет <code>5 минут</code>
            operationId: authRegistration
            parameters:
                - in: body
                  name: Body
                  schema:
                    properties:
                        name:
                            default: Далер
                            description: Имя пользователя
                            type: string
                            x-go-name: Name
                        password:
                            default: '!qwerty123'
                            description: Пароль
                            maxLength: 100
                            minLength: 8
                            type: string
                            x-go-name: Password
                        patronymic:
                            default: Химатджонович
                            description: Отчество пользователя
                            type: string
                            x-go-name: Patronymic
                        phone_number:
                            default: "992911170603"
                            description: Телефонный номер
                            pattern: 992\d{9}$
                            type: string
                            x-go-name: Phone
                        surname:
                            default: Хайраков
                            description: Фамилия пользователя
                            type: string
                            x-go-name: Surname
                    required:
                        - name
                        - surname
                        - patronymic
                        - phone_number
                        - password
                    type: object
            responses:
                "200":
                    description: '## Успешная авторизаиця'
                    schema:
                        $ref: '#/responses/success/schema'
                "400":
                    description: |-
                        ## Неверный запрос
                        Возможно, вам стоит перепроверить введенные данные

                        Все возможные сообщения об ошибках в полезной нагрузке (payload):
                        <ul>
                          <li>Не верный OTP код</li>
                          <li>Ваше имя слишком короткое</li>
                          <li>Ваше имя содержит символы</li>
                          <li>Пароль должен содержать как минимум 8 символов</li>
                        </ul>
                    schema:
                        $ref: '#/responses/badRequest/schema'
                "500":
                    description: Internal Server Error or Something went wrong
                    schema:
                        $ref: '#/responses/internalServer/schema'
            summary: Регистрация нового пользователя
            tags:
                - Authorization
    /ping:
        get:
            description: '## A simple router to check server status'
            operationId: ping
            responses:
                "200":
                    description: "## Pong ! \U0001F94E"
                    schema:
                        $ref: '#/responses/ping/schema'
            summary: Ping Pong!
            tags:
                - Ping
produces:
    - application/json
responses:
    accessDenied:
        description: ""
        schema:
            properties:
                message:
                    example: access is denied
                    type: string
                    x-go-name: Message
                payload:
                    example: "null"
                    x-go-name: Payload
            type: object
    badRequest:
        description: ""
        schema:
            properties:
                message:
                    example: bad request
                    type: string
                    x-go-name: Message
                payload:
                    example: "null"
                    x-go-name: Payload
            type: object
    conflict:
        description: ""
        schema:
            properties:
                message:
                    example: conflict
                    type: string
                    x-go-name: Message
                payload:
                    example: "null"
                    x-go-name: Payload
            type: object
    internalServer:
        description: ""
        schema:
            properties:
                message:
                    example: internal server error
                    type: string
                    x-go-name: Message
                payload:
                    example: "null"
                    x-go-name: Payload
            type: object
    notFound:
        description: ""
        schema:
            properties:
                message:
                    example: notFound
                    type: string
                    x-go-name: Message
                payload:
                    example: "null"
                    x-go-name: Payload
            type: object
    notImplementation:
        description: ""
        schema:
            properties:
                message:
                    example: not implementation
                    type: string
                    x-go-name: Message
                payload:
                    example: "null"
                    x-go-name: Payload
            type: object
    passwordLen:
        description: ""
        headers:
            Data: {}
        schema:
            properties:
                message:
                    default: Пароль должен содержать как минимум 8 символов
                    type: string
                    x-go-name: Message
                payload:
                    default: "null"
                    type: string
                    x-go-name: Payload
            type: object
    ping:
        description: Ping
        headers:
            Data: {}
        schema:
            properties:
                message:
                    default: Успешно
                    type: string
                    x-go-name: Message
                payload:
                    default: "Clean arch pong! \U0001F94E"
                    type: string
                    x-go-name: Payload
            type: object
    retryLimitExceeded:
        description: ""
        schema:
            properties:
                message:
                    example: retry limit exceeded
                    type: string
                    x-go-name: Message
                payload:
                    example: "null"
                    x-go-name: Payload
            type: object
    somethingWentWrong:
        description: ""
        schema:
            properties:
                message:
                    example: something went wrong
                    type: string
                    x-go-name: Message
                payload:
                    example: "null"
                    x-go-name: Payload
            type: object
    success:
        description: ""
        schema:
            properties:
                message:
                    example: success
                    type: string
                    x-go-name: Message
                payload:
                    example: "null"
                    x-go-name: Payload
            type: object
    unauthorized:
        description: ""
        schema:
            properties:
                message:
                    example: unauthorized
                    type: string
                    x-go-name: Message
                payload:
                    example: "null"
                    x-go-name: Payload
            type: object
securityDefinitions:
    Bearer:
        in: header
        name: Authorization
        type: apiKey
swagger: "2.0"
